<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="24960" started-at="2018-07-25T07:18:02Z" finished-at="2018-07-25T07:18:27Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="24895" started-at="2018-07-25T07:18:02Z" finished-at="2018-07-25T07:18:27Z">
      <class name="com.accenture.test.RegistrationTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.accenture.test.RegistrationTest@d8355a8]" name="beforeTest" is-config="true" duration-ms="11567" started-at="2018-07-25T12:48:02Z" finished-at="2018-07-25T12:48:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="f()[pri:0, instance:com.accenture.test.RegistrationTest@d8355a8]" name="f" duration-ms="10938" started-at="2018-07-25T12:48:13Z" finished-at="2018-07-25T12:48:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.accenture.test.RegistrationTest@d8355a8]" name="afterTest" is-config="true" duration-ms="2287" started-at="2018-07-25T12:48:24Z" finished-at="2018-07-25T12:48:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.accenture.test.RegistrationTest -->
    </test> <!-- Test -->
    <test name="Test1" duration-ms="18" started-at="2018-07-25T07:18:27Z" finished-at="2018-07-25T07:18:27Z">
      <class name="com.accenture.test.LoginTest">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.accenture.test.LoginTest@e25b2fe]" name="beforeTest" is-config="true" duration-ms="1" started-at="2018-07-25T12:48:27Z" finished-at="2018-07-25T12:48:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="f()[pri:0, instance:com.accenture.test.LoginTest@e25b2fe]" name="f" duration-ms="11" started-at="2018-07-25T12:48:27Z" finished-at="2018-07-25T12:48:27Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed expected [Ash] but found [Ashvin]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed expected [Ash] but found [Ashvin]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at com.accenture.test.LoginTest.f(LoginTest.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
      </class> <!-- com.accenture.test.LoginTest -->
    </test> <!-- Test1 -->
  </suite> <!-- Suite -->
</testng-results>
